sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t emielvdongen/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true emielvdongen/docker-react npm run test
